In [1]:
# Importing Numpy
import numpy as np

In [5]:
# Creating arrays
a = np.array([i for i in range(1, 11)])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Creating 2D arrays
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Checking the charecteristics of arrays
print("The dimensions of the above array is: ", b.ndim)
print("The shape of the above array is: ", b.shape)
print("The types of values in the above array is: ", b.dtype)
print("The size of each value in the above array is: ", b.itemsize)
print("The total size of the above array is: ", b.nbytes)

The dimensions of the above array is:  2
The shape of the above array is:  (3, 3)
The types of values in the above array is:  int64
The size of each value in the above array is:  8
The total size of the above array is:  72


## Accessing the arrays in different ways

- The most basic way to access a numpy array is through the follow syntax.
- Everything expands on the following syntax

array[`row`, `column`]

In [7]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Accessing the first row from b
print(b[0, :])

[1 2 3]


In [9]:
# Accessing each row individually
for i in range(3):
    print(b[i, :])

[1 2 3]
[4 5 6]
[7 8 9]


In [10]:
# Accessing the first column of b
print(b[:, 0])

[1 4 7]


In [11]:
# Accessing each column individually
for i in range(3):
    print(b[:, i])

[1 4 7]
[2 5 8]
[3 6 9]


In [13]:
print("The original matrix")
print(b)

The original matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Accessing a slice

- While accessing a slice we mention row no first
- For the specified row we use list like slicing in the value for the column

array[`Row`, `Slice of the Column`]

In [14]:
# Accessing a slice of the matrix
print(b[1, :-1])

[4 5]


## Accessing and changing values

In [15]:
# Accessing 5
print(b[1, 1])

5


In [16]:
# Changing a single value
b[1, 1] = 100
print(b)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [17]:
# Changing a row
b[1, :] = 100
print(b)

[[  1   2   3]
 [100 100 100]
 [  7   8   9]]


In [18]:
# Changing a row to predefinied values
b[1, :] = [4, 5, 6]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Changing a column
b[:, 1] = 100
print(b)

[[  1 100   3]
 [  4 100   6]
 [  7 100   9]]


In [20]:
# Changing a column to a predefined value
b[:, 1] = [2, 5, 8]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Initialising to predefined values will only work when the dimensions of the predefined array match the dimensions it is replacing