In [1]:
# Importing Numpy|
import numpy as np

In [2]:
# Creating arrays
a = np.array([i for i in range(1, 11)])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Creating 2D arrays
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Checking the charecteristics of arrays
print("The dimensions of the above array is: ", b.ndim)
print("The shape of the above array is: ", b.shape)
print("The types of values in the above array is: ", b.dtype)
print("The size of each value in the above array is: ", b.itemsize)
print("The total size of the above array is: ", b.nbytes)

The dimensions of the above array is:  2
The shape of the above array is:  (3, 3)
The types of values in the above array is:  int64
The size of each value in the above array is:  8
The total size of the above array is:  72


## Accessing the arrays in different ways

- The most basic way to access a numpy array is through the follow syntax.
- Everything expands on the following syntax

array[`row`, `column`]

In [5]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Accessing the first row from b
print(b[0, :])

[1 2 3]


In [7]:
# Accessing each row individually
for i in range(3):
    print(b[i, :])

[1 2 3]
[4 5 6]
[7 8 9]


In [8]:
# Accessing the first column of b
print(b[:, 0])

[1 4 7]


In [9]:
# Accessing each column individually
for i in range(3):
    print(b[:, i])

[1 4 7]
[2 5 8]
[3 6 9]


In [10]:
print("The original matrix")
print(b)

The original matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Accessing a slice

- While accessing a slice we mention row no first
- For the specified row we use list like slicing in the value for the column

array[`Row`, `Slice of the Column`]

In [11]:
# Accessing a slice of the matrix
print(b[1, :-1])

[4 5]


## Accessing and changing values

In [12]:
# Accessing 5
print(b[1, 1])

5


In [13]:
# Changing a single value
b[1, 1] = 100
print(b)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [14]:
# Changing a row
b[1, :] = 100
print(b)

[[  1   2   3]
 [100 100 100]
 [  7   8   9]]


In [15]:
# Changing a row to predefinied values
b[1, :] = [4, 5, 6]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Changing a column
b[:, 1] = 100
print(b)

[[  1 100   3]
 [  4 100   6]
 [  7 100   9]]


In [17]:
# Changing a column to a predefined value
b[:, 1] = [2, 5, 8]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Initialising to predefined values will only work when the dimensions of the predefined array match the dimensions it is replacing

## Initialising Special Arrays

In [18]:
# Initialise an array of zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Initialise an array of ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Initialise an array with other numbers
np.full((3, 3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [21]:
# Initialise an array of other numbers similar to a previous array
np.full_like(b.shape, -1000)

array([-1000, -1000])

In [23]:
# Initialise an array of random numbers between 0 and 1
np.random.rand(4, 4)

array([[0.5957258 , 0.72508457, 0.22713577, 0.19388094],
       [0.61595456, 0.25686851, 0.00834505, 0.10397399],
       [0.44842589, 0.0389936 , 0.87698746, 0.90878951],
       [0.84199244, 0.08909439, 0.26757683, 0.17308926]])

In [26]:
# Initialise an array of random numbers similar to a previous array
np.random.random_sample(b.shape)

array([[0.62020265, 0.00197057, 0.14524072],
       [0.78901738, 0.42086677, 0.36031987],
       [0.2460226 , 0.8699597 , 0.46182405]])

In [27]:
# Initialise a random array of integers
np.random.randint(4, 10, (6, 6))

array([[6, 6, 7, 6, 9, 5],
       [6, 5, 8, 9, 9, 4],
       [8, 5, 8, 9, 7, 8],
       [7, 5, 8, 5, 8, 6],
       [8, 6, 6, 4, 4, 8],
       [6, 7, 9, 9, 9, 4]])

In [28]:
# Initialise an identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])