In [1]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

In [3]:
# Loading the dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
# Splitting the features and targets
X_train = iris.data
y_train = iris.target

In [5]:
# Checking the features and targets
print(f"Features: {iris.feature_names}")
print(f"Features: {iris.target_names}")

Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Features: ['setosa' 'versicolor' 'virginica']


In [9]:
# Desigining the classification model
model = Sequential([
    Dense(units = 4, activation = "relu"),
    Dense(units = 3, activation = "relu"),
    Dense(units = 3, activation = "softmax")
])

# Compiling the model
model.compile(loss = "SparseCategoricalCrossentropy", optimizer = "adam", metrics = ["accuracy"])

# Training the model
model.fit(X_train, y_train, epochs = 500)

Epoch 1/500
5/5 [==============================] - 0s 10ms/step - loss: 2.0213 - accuracy: 0.3333
Epoch 2/500
5/5 [==============================] - 0s 5ms/step - loss: 1.9348 - accuracy: 0.3333
Epoch 3/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8528 - accuracy: 0.3333
Epoch 4/500
5/5 [==============================] - 0s 5ms/step - loss: 1.7760 - accuracy: 0.3333
Epoch 5/500
1/5 [=====>........................] - ETA: 0s - loss: 1.7475 - accuracy: 0.3438

2023-02-14 20:25:52.100614: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


5/5 [==============================] - 0s 5ms/step - loss: 1.7064 - accuracy: 0.3333
Epoch 6/500
5/5 [==============================] - 0s 5ms/step - loss: 1.6388 - accuracy: 0.3333
Epoch 7/500
5/5 [==============================] - 0s 5ms/step - loss: 1.5747 - accuracy: 0.3333
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 1.5220 - accuracy: 0.3333
Epoch 9/500
5/5 [==============================] - 0s 5ms/step - loss: 1.4690 - accuracy: 0.3333
Epoch 10/500
5/5 [==============================] - 0s 5ms/step - loss: 1.4223 - accuracy: 0.3333
Epoch 11/500
5/5 [==============================] - 0s 5ms/step - loss: 1.3785 - accuracy: 0.3333
Epoch 12/500
5/5 [==============================] - 0s 5ms/step - loss: 1.3400 - accuracy: 0.3333
Epoch 13/500
5/5 [==============================] - 0s 5ms/step - loss: 1.3043 - accuracy: 0.3333
Epoch 14/500
5/5 [==============================] - 0s 5ms/step - loss: 1.2713 - accuracy: 0.3333
Epoch 15/500
5/5 [===================

5/5 [==============================] - 0s 4ms/step - loss: 0.7819 - accuracy: 0.6533
Epoch 89/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7787 - accuracy: 0.6533
Epoch 90/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7756 - accuracy: 0.6533
Epoch 91/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7725 - accuracy: 0.6533
Epoch 92/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7695 - accuracy: 0.6533
Epoch 93/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7666 - accuracy: 0.6533
Epoch 94/500
5/5 [==============================] - 0s 5ms/step - loss: 0.7637 - accuracy: 0.6533
Epoch 95/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7607 - accuracy: 0.6533
Epoch 96/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7579 - accuracy: 0.6533
Epoch 97/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7551 - accuracy: 0.6533
Epoch 98/500
5/5 [===============

5/5 [==============================] - 0s 5ms/step - loss: 0.6178 - accuracy: 0.6867
Epoch 172/500
5/5 [==============================] - 0s 5ms/step - loss: 0.6163 - accuracy: 0.6867
Epoch 173/500
5/5 [==============================] - 0s 5ms/step - loss: 0.6149 - accuracy: 0.6933
Epoch 174/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6136 - accuracy: 0.6867
Epoch 175/500
5/5 [==============================] - 0s 5ms/step - loss: 0.6122 - accuracy: 0.6867
Epoch 176/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6108 - accuracy: 0.6867
Epoch 177/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6095 - accuracy: 0.6867
Epoch 178/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6081 - accuracy: 0.6867
Epoch 179/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6069 - accuracy: 0.6867
Epoch 180/500
5/5 [==============================] - 0s 5ms/step - loss: 0.6055 - accuracy: 0.6933
Epoch 181/500
5/5 [=====

5/5 [==============================] - 0s 4ms/step - loss: 0.5198 - accuracy: 0.8000
Epoch 254/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5186 - accuracy: 0.8000
Epoch 255/500
5/5 [==============================] - 0s 5ms/step - loss: 0.5175 - accuracy: 0.8000
Epoch 256/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5167 - accuracy: 0.8067
Epoch 257/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5155 - accuracy: 0.8067
Epoch 258/500
5/5 [==============================] - 0s 5ms/step - loss: 0.5144 - accuracy: 0.8000
Epoch 259/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5134 - accuracy: 0.8000
Epoch 260/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5122 - accuracy: 0.8000
Epoch 261/500
5/5 [==============================] - 0s 4ms/step - loss: 0.5111 - accuracy: 0.8000
Epoch 262/500
5/5 [==============================] - 0s 5ms/step - loss: 0.5100 - accuracy: 0.8067
Epoch 263/500
5/5 [=====

5/5 [==============================] - 0s 4ms/step - loss: 0.4326 - accuracy: 0.9067
Epoch 336/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4315 - accuracy: 0.9067
Epoch 337/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4306 - accuracy: 0.9067
Epoch 338/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4295 - accuracy: 0.9067
Epoch 339/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4284 - accuracy: 0.9067
Epoch 340/500
5/5 [==============================] - 0s 5ms/step - loss: 0.4272 - accuracy: 0.9067
Epoch 341/500
5/5 [==============================] - 0s 5ms/step - loss: 0.4265 - accuracy: 0.9067
Epoch 342/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4253 - accuracy: 0.9067
Epoch 343/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4241 - accuracy: 0.9067
Epoch 344/500
5/5 [==============================] - 0s 4ms/step - loss: 0.4230 - accuracy: 0.9067
Epoch 345/500
5/5 [=====

5/5 [==============================] - 0s 4ms/step - loss: 0.3454 - accuracy: 0.9267
Epoch 418/500
5/5 [==============================] - 0s 4ms/step - loss: 0.3435 - accuracy: 0.9267
Epoch 419/500
5/5 [==============================] - 0s 5ms/step - loss: 0.3424 - accuracy: 0.9267
Epoch 420/500
5/5 [==============================] - 0s 4ms/step - loss: 0.3413 - accuracy: 0.9333
Epoch 421/500
5/5 [==============================] - 0s 4ms/step - loss: 0.3403 - accuracy: 0.9467
Epoch 422/500
5/5 [==============================] - 0s 5ms/step - loss: 0.3397 - accuracy: 0.9467
Epoch 423/500
5/5 [==============================] - 0s 5ms/step - loss: 0.3383 - accuracy: 0.9467
Epoch 424/500
5/5 [==============================] - 0s 5ms/step - loss: 0.3372 - accuracy: 0.9400
Epoch 425/500
5/5 [==============================] - 0s 5ms/step - loss: 0.3365 - accuracy: 0.9400
Epoch 426/500
5/5 [==============================] - 0s 4ms/step - loss: 0.3349 - accuracy: 0.9400
Epoch 427/500
5/5 [=====

5/5 [==============================] - 0s 4ms/step - loss: 0.2622 - accuracy: 0.9733
Epoch 500/500
5/5 [==============================] - 0s 4ms/step - loss: 0.2612 - accuracy: 0.9733


In [10]:
model.get_weights()

[array([[-0.56446964,  0.40058017,  0.3203351 , -0.85440487],
        [ 0.01205621, -0.55122334, -0.35917443,  0.8524621 ],
        [ 1.168922  ,  0.31171492, -0.5808208 , -0.63313884],
        [ 0.4033394 ,  0.08415917,  0.12280542,  0.01680964]],
       dtype=float32),
 array([-0.4718324 , -0.15819672,  0.        ,  0.        ], dtype=float32),
 array([[-0.34849173,  0.8504253 ,  1.435393  ],
        [-0.91339725,  0.6109785 , -0.22964646],
        [-0.3839736 ,  0.91132045,  0.8482443 ],
        [ 0.10412359, -0.6209235 , -0.6768539 ]], dtype=float32),
 array([ 0.       , -0.2775567, -1.1520145], dtype=float32),
 array([[-0.37641406,  0.65268254,  0.36989117],
        [-1.3954054 ,  0.62285537, -0.07428678],
        [-2.1252608 ,  0.06921846,  2.1460023 ]], dtype=float32),
 array([ 1.6532779 , -0.31133425, -1.5263835 ], dtype=float32)]

In [11]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 4)                 20        
                                                                 
 dense_10 (Dense)            (None, 3)                 15        
                                                                 
 dense_11 (Dense)            (None, 3)                 12        
                                                                 
Total params: 47
Trainable params: 47
Non-trainable params: 0
_________________________________________________________________


In [16]:
# Predicting using the model
model.predict([[5.1, 3.5, 1.4, 0.2]])

1/1 [==============================] - 0s 20ms/step


array([[0.8461597 , 0.11864027, 0.03520002]], dtype=float32)

In [17]:
model.predict([[6.4, 3.2, 4.5, 1.5]])

1/1 [==============================] - 0s 19ms/step


array([[0.00337275, 0.7342425 , 0.2623848 ]], dtype=float32)

In [19]:
model.predict([[6.3, 3.3, 6.0, 2.5]])

1/1 [==============================] - 0s 20ms/step


array([[1.4380488e-09, 2.0897793e-02, 9.7910219e-01]], dtype=float32)